# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from pathlib import Path as _Path
from PySide6 import QtCore, QtGui, QtWidgets

_ICONS_DIR = str(_Path(__file__).resolve().parent / "icons")


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(884, 637)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(30)
        Form.setFont(font)
        Form.setStyleSheet("""
/* ── Formulaire conteneur ────────────────────────────── */
#info_frame {
    background-color: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 10px;
}

/* ── Labels ──────────────────────────────────────────── */
#info_frame QLabel {
    font-family: 'Segoe UI', Helvetica, Arial, sans-serif;
    font-size: 11px;
    font-weight: 700;
    color: #374151;
}

/* ── Champs texte, ComboBox, DateEdit ────────────────── */
#info_frame QLineEdit,
#info_frame QComboBox,
#info_frame QDateEdit {
    font-family: 'Segoe UI', Helvetica, Arial, sans-serif;
    font-size: 10px;
    color: #1f2937;
    padding: 1px 6px;
    border: 1px solid #d1d5db;
    border-radius: 4px;
    background-color: #f9fafb;
    min-height: 20px;
    max-height: 22px;
}

#info_frame QLineEdit:focus,
#info_frame QComboBox:focus,
#info_frame QDateEdit:focus {
    border: 2px solid #003f8a;
    background-color: #ffffff;
}

#info_frame QLineEdit:hover,
#info_frame QComboBox:hover,
#info_frame QDateEdit:hover {
    border-color: #9ca3af;
    background-color: #ffffff;
}

/* ── ComboBox flèche ─────────────────────────────────── */
QComboBox::drop-down {
    background: transparent;
    border: none;
    width: 20px;
}

/* ── DateEdit bouton calendrier ──────────────────────── */
QDateEdit::drop-down {
    background: transparent;
    border: none;
    width: 20px;
}

/* ── Conteneur tableau ───────────────────────────────── */
#result_frame {
    border-radius: 10px;
    background-color: #ffffff;
    border: 1px solid #e2e8f0;
}

/* ── En-tête du tableau ──────────────────────────────── */
QHeaderView::section {
    background-color: #003f8a;
    color: #ffffff;
    font-family: 'Segoe UI', Helvetica, Arial, sans-serif;
    font-size: 11px;
    font-weight: 700;
    border: none;
    border-right: 1px solid #0077c8;
    border-bottom: 2px solid #0077c8;
    padding: 7px 8px;
    text-align: left;
}
QHeaderView::section:last-of-type {
    border-right: none;
}

/* ── Cellules du tableau ─────────────────────────────── */
QTableWidget::item {
    border-bottom: 1px solid #e5e7eb;
    color: #1f2937;
    padding: 3px 6px;
    font-family: 'Segoe UI', Helvetica, Arial, sans-serif;
    font-size: 11px;
}
QTableWidget::item:selected {
    background-color: #dbeafe;
    color: #003f8a;
}
QTableWidget::item:hover {
    background-color: #eff6ff;
}

/* ── Boutons barre actions ───────────────────────────── */
#function_frame QPushButton {
    font-family: 'Segoe UI', Helvetica, Arial, sans-serif;
    font-size: 12px;
    font-weight: 600;
    padding: 7px 18px;
    border: none;
    border-radius: 8px;
    color: #ffffff;
    background-color: #003f8a;
}
#function_frame QPushButton:hover {
    background-color: #0077c8;
}
#function_frame QPushButton:pressed {
    background-color: #002d66;
}

/* Ajouter → vert */
#function_frame #add_btn {
    background-color: #059669;
}
#function_frame #add_btn:hover {
    background-color: #047857;
}
#function_frame #add_btn:pressed {
    background-color: #065f46;
}

/* Mettre à jour → bleu CNPS */
#function_frame #update_btn {
    background-color: #0077c8;
}
#function_frame #update_btn:hover {
    background-color: #003f8a;
}

/* Effacer → gris ardoise */
#function_frame #clear_btn {
    background-color: #64748b;
}
#function_frame #clear_btn:hover {
    background-color: #475569;
}

/* Supprimer → rouge */
#function_frame #delete_btn {
    background-color: #dc2626;
}
#function_frame #delete_btn:hover {
    background-color: #b91c1c;
}
#function_frame #delete_btn:pressed {
    background-color: #991b1b;
}
""")
        self.gridLayout_5 = QtWidgets.QGridLayout(Form)
        self.gridLayout_5.setContentsMargins(20, -1, 20, 20)
        self.gridLayout_5.setVerticalSpacing(15)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_3 = QtWidgets.QFrame(parent=Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.setStyleSheet(
            "QFrame { background: qlineargradient(x1:0,y1:0,x2:1,y2:0,"
            "stop:0 #003f8a, stop:1 #0077c8);"
            "border-radius: 8px; }"
        )
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(20, 14, 20, 14)
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_label = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignVCenter | QtCore.Qt.AlignmentFlag.AlignLeft)
        self.title_label.setStyleSheet(
            "color: white; background: transparent; letter-spacing: 1px;"
        )
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_2.addWidget(self.title_label)
        self.horizontalLayout_2.addStretch(1)
        self.gridLayout_5.addWidget(self.frame_3, 0, 0, 1, 1)
        self.function_frame = QtWidgets.QFrame(parent=Form)
        self.function_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.function_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.function_frame.setObjectName("function_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.function_frame)
        self.horizontalLayout.setContentsMargins(30, 10, 30, 10)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Bouton Mettre à jour (on le garde dans la barre)
        self.update_btn = QtWidgets.QPushButton(parent=self.function_frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(f"{_ICONS_DIR}/update.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.update_btn.setIcon(icon1)
        self.update_btn.setIconSize(QtCore.QSize(20, 20))
        self.update_btn.setObjectName("update_btn")
        self.horizontalLayout.addWidget(self.update_btn)

        # Bouton Effacer (formulaire)
        self.clear_btn = QtWidgets.QPushButton(parent=self.function_frame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(f"{_ICONS_DIR}/clear.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clear_btn.setIcon(icon4)
        self.clear_btn.setIconSize(QtCore.QSize(20, 20))
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout.addWidget(self.clear_btn)

        # Boutons Ajouter / Sélectionner / Supprimer conservés mais masqués (non affichés)
        self.add_btn = QtWidgets.QPushButton(parent=self.function_frame)
        self.add_btn.setObjectName("add_btn")
        self.add_btn.hide()
        self.select_btn = QtWidgets.QPushButton(parent=self.function_frame)
        self.select_btn.setObjectName("select_btn")
        self.select_btn.hide()
        self.delete_btn = QtWidgets.QPushButton(parent=self.function_frame)
        self.delete_btn.setObjectName("delete_btn")
        self.delete_btn.hide()
        self.gridLayout_5.addWidget(self.function_frame, 2, 0, 1, 1)
        self.result_frame = QtWidgets.QFrame(parent=Form)
        self.result_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.result_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.result_frame.setObjectName("result_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.result_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.result_frame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(21)
        self.tableWidget.setObjectName("tableWidget")
        # 23 colonnes existantes + 10 colonnes supplémentaires (schéma complet)
        # + 4 colonnes complémentaires (actions_menees, téléphone_2, email_2, email_3)
        # + 1 colonne "STATUT"
        self.tableWidget.setColumnCount(38)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        # Création des items d'en-têtes pour 38 colonnes
        for col in range(38):
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter)
            if col <= 5:
                font = QtGui.QFont()
                font.setFamily("黑体")
                font.setPointSize(10)
                item.setFont(font)
            self.tableWidget.setHorizontalHeaderItem(col, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(26)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.result_frame, 3, 0, 1, 1)
        self.info_frame = QtWidgets.QFrame(parent=Form)
        self.info_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.info_frame.setObjectName("info_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.info_frame)
        self.gridLayout_6.setContentsMargins(12, 6, 12, 6)
        self.gridLayout_6.setHorizontalSpacing(12)
        self.gridLayout_6.setVerticalSpacing(4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.info_frame)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.info_frame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.info_frame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.info_frame)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.info_frame)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.info_frame)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.info_frame)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.info_frame, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SUIVI ALIMENTATION DES CARRIERES ASSURES"))
        self.title_label.setText(_translate("Form", "SUIVI ALIMENTATION DES CARRIERES ASSURES"))
        self.add_btn.setText(_translate("Form", "Ajouter"))
        self.update_btn.setText(_translate("Form", "Mettre à jour"))
        self.select_btn.setText(_translate("Form", "Sélectionner"))
        self.clear_btn.setText(_translate("Form", "Effacer"))
        self.delete_btn.setText(_translate("Form", "Supprimer"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("Form", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("Form", "2"))
        # Colonnes d'identification des employeurs (0 à 10)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "N°"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "NUMERO CNPS"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "RAISON SOCIALE"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "SECTEUR D' ACTIVITE"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "EFFECTIFS"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "PERIODICITE"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "NUMERO TELEPHONE"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "MAIL"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "LOCALITES"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "EXERCICE"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Form", "DISA ANTERIEUR A RECUEILLIR"))

        # Colonnes de traitement DISA (11 à 22)
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Form", "DATE DE RECEPTION"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Form", "DATE DE TRAITEMENT"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("Form", "DATE DE VALIDATION"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("Form", "EFFECTIF DISA"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("Form", "NBRE DE LIGNES TRAITEES"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("Form", "NBRE DE LIGNES VALIDEES"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("Form", "NBRE DE LIGNES REJETEES"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("Form", "NBRE DE LIGNES REJETEES TRAITEES"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("Form", "NBRE TOTAL DE LIGNES VALIDEES APRES TRAITEMENT DES REJETS"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("Form", "DATE DE TRAITEMENT REJET"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("Form", "NBRE RESTANT DE REJET"))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("Form", "OBSERVATIONS"))

        # Colonnes supplémentaires (23 à 32) pour les champs restants du schéma
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("Form", "ID EMPLOYEUR"))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("Form", "DATE DE DEBUT ACTIVITE"))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("Form", "FORME JURIDIQUE"))
        item = self.tableWidget.horizontalHeaderItem(26)
        item.setText(_translate("Form", "DISA 2024"))
        item = self.tableWidget.horizontalHeaderItem(27)
        item.setText(_translate("Form", "DISA 2023"))
        item = self.tableWidget.horizontalHeaderItem(28)
        item.setText(_translate("Form", "DISA 2022"))
        item = self.tableWidget.horizontalHeaderItem(29)
        item.setText(_translate("Form", "DISA 2021"))
        item = self.tableWidget.horizontalHeaderItem(30)
        item.setText(_translate("Form", "DISA ANTERIEURES 2010-2020"))
        item = self.tableWidget.horizontalHeaderItem(31)
        item.setText(_translate("Form", "LOCALISATION GEOGRAPHIQUE"))
        item = self.tableWidget.horizontalHeaderItem(32)
        item.setText(_translate("Form", "ID TRAITEMENT"))
        item = self.tableWidget.horizontalHeaderItem(33)
        item.setText(_translate("Form", "STATUT"))
        item = self.tableWidget.horizontalHeaderItem(34)
        item.setText(_translate("Form", "ACTIONS MENÉES"))
        item = self.tableWidget.horizontalHeaderItem(35)
        item.setText(_translate("Form", "NUMERO TELEPHONE 2"))
        item = self.tableWidget.horizontalHeaderItem(36)
        item.setText(_translate("Form", "MAIL 2"))
        item = self.tableWidget.horizontalHeaderItem(37)
        item.setText(_translate("Form", "MAIL 3"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", ""))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", ""))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", ""))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("Form", ""))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "N°"))
        self.label_2.setText(_translate("Form", "Numéro CNPS"))
        self.label_3.setText(_translate("Form", "Raison sociale"))
        self.label_4.setText(_translate("Form", "Secteur d'activité"))
        self.comboBox.setItemText(1, _translate("Form", "Nouvel élément"))
        self.comboBox.setItemText(2, _translate("Form", "Nouvel élément"))
        self.comboBox.setItemText(3, _translate("Form", "Nouvel élément"))
        self.comboBox.setItemText(4, _translate("Form", "Nouvel élément"))
        self.label_5.setText(_translate("Form", "Effectifs"))
        self.comboBox_2.setItemText(1, _translate("Form", "Nouvel élément"))
        self.comboBox_2.setItemText(2, _translate("Form", "Nouvel élément"))
        self.comboBox_2.setItemText(3, _translate("Form", "Nouvel élément"))
        self.comboBox_2.setItemText(4, _translate("Form", "Nouvel élément"))
        self.comboBox_2.setItemText(5, _translate("Form", "Nouvel élément"))
        self.label_6.setText(_translate("Form", "Périodicité"))
